export const INDUSTRIES = [
  { value: "cafe", label: "카페·커피숍" },
  { value: "restaurant", label: "식당·음식점" },
  { value: "chicken", label: "치킨집·배달음식" },
  { value: "bakery", label: "베이커리·제과점" },
  { value: "beauty_salon", label: "미용실·헤어샵" },
  { value: "nail", label: "네일샵" },
  { value: "skin_care", label: "피부관리샵" },
  { value: "fitness", label: "헬스장·PT샵" },
  { value: "yoga_pilates", label: "요가·필라테스" },
  { value: "clinic", label: "병원·의원" },
  { value: "dental", label: "치과" },
  { value: "pharmacy", label: "약국" },
  { value: "clothing", label: "의류·패션샵" },
  { value: "kids_clothing", label: "아동복·유아용품" },
  { value: "pet", label: "반려동물·펫샵" },
  { value: "pet_grooming", label: "펫그루밍" },
  { value: "flower", label: "꽃집·플라워샵" },
  { value: "interior", label: "인테리어·가구" },
  { value: "cleaning", label: "청소·세탁" },
  { value: "education", label: "학원·교육" },
  { value: "kids_education", label: "어린이집·유치원" },
  { value: "music_art", label: "음악·미술 레슨" },
  { value: "photo", label: "사진관·스튜디오" },
  { value: "travel", label: "여행사·숙박" },
  { value: "real_estate", label: "부동산·공인중개사" },
  { value: "auto_repair", label: "자동차 수리·세차" },
  { value: "electronics", label: "전자제품·수리" },
  { value: "book", label: "서점·문구" },
  { value: "sports", label: "스포츠용품" },
  { value: "health_food", label: "건강식품·보약" },
  { value: "spa", label: "스파·마사지" },
  { value: "tattoo", label: "타투·반영구" },
  { value: "wedding", label: "웨딩·결혼식" },
  { value: "catering", label: "케이터링·출장뷔페" },
  { value: "bar", label: "술집·바" },
  { value: "dessert", label: "디저트·아이스크림" },
  { value: "sushi", label: "초밥·일식" },
  { value: "chinese", label: "중식당" },
  { value: "western", label: "양식·스테이크" },
  { value: "korean", label: "한식당" },
  { value: "convenience", label: "편의점·마트" },
  { value: "accounting", label: "세무사·회계사" },
  { value: "law", label: "법무사·법률사무소" },
  { value: "insurance", label: "보험·금융" },
  { value: "printing", label: "인쇄·출력" },
  { value: "moving", label: "이사·물류" },
  { value: "childcare", label: "산후조리·아기돌봄" },
  { value: "senior_care", label: "노인복지·요양" },
  { value: "craft", label: "공방·핸드메이드" },
  { value: "other", label: "기타 업종" },
] as const;

export const CHANNELS = [
  {
    value: "instagram",
    label: "인스타그램",
    description: "피드 + 해시태그 최적화",
    icon: "📸",
    color: "from-pink-500 to-orange-400",
    bgColor: "bg-gradient-to-br from-pink-50 to-orange-50",
    borderColor: "border-pink-200",
  },
  {
    value: "naver_blog",
    label: "네이버 블로그",
    description: "SEO 최적화 장문 포스팅",
    icon: "📝",
    color: "from-green-500 to-emerald-400",
    bgColor: "bg-gradient-to-br from-green-50 to-emerald-50",
    borderColor: "border-green-200",
  },
  {
    value: "threads",
    label: "스레드",
    description: "500자 이내 감성 글",
    icon: "🧵",
    color: "from-gray-700 to-gray-900",
    bgColor: "bg-gradient-to-br from-gray-50 to-slate-50",
    borderColor: "border-gray-200",
  },
  {
    value: "kakao",
    label: "카카오채널",
    description: "친근한 소식 발행",
    icon: "💬",
    color: "from-yellow-400 to-amber-500",
    bgColor: "bg-gradient-to-br from-yellow-50 to-amber-50",
    borderColor: "border-yellow-200",
  },
] as const;

export const TONES = [
  { value: "friendly", label: "친근하고 따뜻한" },
  { value: "professional", label: "전문적이고 신뢰감 있는" },
  { value: "fun", label: "유쾌하고 재미있는" },
  { value: "luxurious", label: "고급스럽고 세련된" },
  { value: "informative", label: "정보 전달 위주의" },
  { value: "promotional", label: "프로모션·이벤트 강조" },
] as const;

export const CONTENT_PURPOSES = [
  { value: "introduce", label: "가게/서비스 소개" },
  { value: "promotion", label: "할인·이벤트 안내" },
  { value: "new_menu", label: "신메뉴·신상품 출시" },
  { value: "review", label: "리뷰·후기 유도" },
  { value: "daily", label: "일상 공유" },
  { value: "tips", label: "유용한 팁·정보 제공" },
  { value: "season", label: "계절·시즌 콘텐츠" },
] as const;

export type Industry = typeof INDUSTRIES[number]["value"];
export type Channel = typeof CHANNELS[number]["value"];
export type Tone = typeof TONES[number]["value"];
export type ContentPurpose = typeof CONTENT_PURPOSES[number]["value"];

export const PRICING_PLANS = [
  {
    name: "스타터",
    price: 9900,
    description: "프리랜서·1인 사업자에게 적합",
    features: [
      "채널 연결 최대 2개",
      "월 발행 20건",
      "AI 콘텐츠 생성 (기본)",
      "기본 성과 지표",
      "1인 계정",
    ],
    highlighted: false,
    cta: "무료로 시작하기",
  },
  {
    name: "비즈니스",
    price: 29000,
    description: "소상공인·소규모 팀에게 최적",
    features: [
      "채널 연결 최대 5개",
      "월 발행 80건",
      "AI 콘텐츠 생성 (고급 + 캘린더)",
      "상세 분석 + PDF 리포트",
      "팀 계정 최대 3명",
    ],
    highlighted: true,
    cta: "14일 무료 체험",
  },
  {
    name: "에이전시",
    price: 79000,
    description: "마케팅 에이전시를 위한 플랜",
    features: [
      "채널 연결 무제한",
      "월 발행 무제한",
      "AI 콘텐츠 생성 (프리미엄)",
      "화이트라벨 리포트",
      "팀 + 클라이언트 계정 무제한",
    ],
    highlighted: false,
    cta: "문의하기",
  },
] as const;
